### PR TITLE
[#111678348] SSL cert verify for internal Diego Communication

### PR DESCRIPTION
**Pull request by combor**
## What

As we are verifying SSL certificates everywhere there is no reason to skip verification for internal Diego components.

## How to review

Deploy from this branch and check if tests pass. 

## Who can review

NOT @combor

### CODE REVIEW

**Comment by dcarley** [comment]
Looks like this has pulled in some unrelated commits from Alex. Does it need rebasing against master?

**Comment by combor** [comment]
Fixed.

**Comment by dcarley** [comment]
Looks like this is used by the jobs that currently live on our colocated VM:

- https://github.com/cloudfoundry/capi-release/search?utf8=%E2%9C%93&q=skip_cert_verify&type=Code

Confirmed that they now use `-skipCertVerify=false` (or variations thereof) 👍 

Acceptance tests failed on something that seems unrelated though. I'm re-running them.

**Comment by dcarley** [comment]
Tests passed this time. I'm convinced that it was unrelated.

**Pull request merged**
