### PR TITLE
[#117991263] Update concourse browser plugin for new version.

### PR DESCRIPTION
**Pull request by alext**
## What

Some of the markup has changed with the new version of Concourse, so we need to update this plugin so that the dashboard continues to lack cruft.

## How to review

* Add the plugin to your browser as described in the [README](concourse/chrome_plugin/README.md). 
* Verify that the legend, and lower-right details are removed.
* Verify that the top navbar is replaced with parts of the hostname.

## Who can review

Anyone but myself.

### CODE REVIEW

**Comment by dcarley** [comment]
Tested in Chrome against my dev Deployer. The bottom-left legend is removed, but the following isn't:

- bottom-right download links and version
- top-left group tabs

screen shot 2016-07-29 at 10 01 15

Could you add some detail to the commit message about what wasn't working and what should now be fixed?

**Comment by alext** [comment]
@dcarley Any chance you could past any errors from the developer console here.  It was working for me. What you're describing is what I'd expect with the old version.

**Comment by dcarley** [comment]
Sure:
```
Uncaught TypeError: Cannot read property 'parentNode' of null
  (anonymous function) @inject.user.js:19
```

**Comment by dcarley** [comment]
Oh, that's not the right version of the plugin, bear with me..

**Comment by dcarley** [comment]
Yeah, it was my bad. Finder search brought up a different clone of `paas-cf` from my GOPATH 😞 

It does work as described. Could you update the commit message?

**Comment by alext** [comment]
Commit message updated.

**Comment by dcarley** [comment]
Thanks 👍

**Pull request merged**
