### PR TITLE
[docs] Change self-update instructions for DataDog in dev

### PR DESCRIPTION
**Pull request by dcarley**
## What

Replace the sentence, which says what to do if you have self-update
pipelines disabled but not what to do if you don't, with a command to
also disable self-update pipelines.

Because I copied the command without reading the preceding sentence, so
self-update pipeline overwrote my changes and I was left momentarily
confused.

## How to review

Text review only should be sufficient.

## Who can review

Not @dcarley

### CODE REVIEW

**Comment by dcarley** [comment]
Travis build failed due to a problem in Travis:
```
The command "sudo -E apt-add-repository -y "ppa:git-core/ppa"" failed and exited with 1 during .
```

I've restarted the build and it now passes.

**Comment by mtekel** [comment]
LG, would be also nice to fix numbering, because on github, all steps display as 1.

**Comment by dcarley** [comment]
> LG, would be also nice to fix numbering, because on github, all steps display as 1.

Good point. Pushed a commit to fix it.

**Comment by mtekel** [comment]
thanks, merging

**Pull request merged**
