### PR TITLE
Add .idea directory to .gitignore

### PR DESCRIPTION
**Pull request by benhyland**
## What

Add `.idea/` to `.gitignore`.

Prefer adding to the project rather than the global gitignore,
since other non-PaaS projects may choose to commit IDE config files.

## How to review

No special advice.

## Who can review

Anyone except @benhyland

### CODE REVIEW

**Comment by keymon** [comment]
Fine with me, but I will close this one and open it again. the reason is that I think this will break the automated script that we have for merge PRs.

**Comment by keymon** [comment]
https://github.com/alphagov/paas-cf/pull/358

**Comment by mtekel** [comment]
@keymon merge script works also for this kind of PRs. See #354

**Comment by keymon** [comment]
I see, sorry I assume it wouldn't.

Now is done, only more work for me :)

**Pull request closed without merging**
