### PR TITLE
Update makefile help generation

### PR DESCRIPTION
**Pull request by whi-tw**
What
----

Rather than the old way of just pulling out the targets, categorise and sort the targets into categories and then alphabetically sort the targets within these groups. This allows targets to be identified and found easier.

This script isn't intended to be run manually - it is the default target in the Makefile, so is only run if running `make` with no  arguments, or `make help`

How to review
-------------

Run `make help` and ensure the output is sensible

---

🚨⚠️ Please do not merge this pull request via the GitHub UI ⚠️🚨

### CODE REVIEW

**Comment by whi-tw** [comment]
(tagged some random people for review, no real demand that you do it - don't worry!)

**Comment by paroxp** [comment]
Would you be able to document usage of the script and describe when one should be using it?

**Comment by whi-tw** [comment]
> Would you be able to document usage of the script and describe when one should be using it?

Hopefully that's more better! 💎

**Comment by whi-tw** [comment]
This is really just a nice-to-have, and not really something people should spend time reviewing!

**Pull request closed without merging**
