### PR TITLE
Improve debugging and operating paas-metrics

### PR DESCRIPTION
**Pull request by 46bit**
What
----

This PR does two things:

* Ship logs to Logit from `paas-metrics` and the other apps in the `admin/monitoring` space
* Allow up to 10 minutes for `paas-metrics` to start emitting its metrics

Both of these will help with recent pipeline failures in London:

* Some causes of pipeline failures were from metrics which did show up after a few minutes. Allowing 10 minutes will stop the pipeline failing
* Another cause of pipeline failures is the `paas_aws_elasticache_cache_parameter_group_count` metric breaking for a day at a time. Shipping logs will allow us to debug if that happens again

How to review
-------------

Try deploy it

Who can review
--------------

Not @46bit

### CODE REVIEW

**Comment by 46bit** [comment]
I'm running this through my dev env. Will update when it works.

**Comment by tlwr** [comment]
Is the `Eventually(metricFamilies)` going to work in this context:

- `Eventually`s default timeout is 1s and it polls every 10ms (although I haven't checked if this is overridden in the suite)
- `metricFamilies` is assigned once in the `BeforeSuite` rather than checked periodically

**Comment by 46bit** [comment]
Uhh, this is missing some of my work 😮 thanks toby!

**Comment by tlwr** [comment]
Silly me, I just noticed this was a draft, sorry!

**Comment by 46bit** [comment]
Closed by #2469. Thanks @tlwr.

**Pull request closed without merging**
