### PR TITLE
[#167971884] Switch paas-pass secrets from s3 to credhub

### PR DESCRIPTION
**Pull request by richardTowers**
~**Conflicts with #2057 - we either need to review / merge that first and update this or the other way around**~ *Done*.

What
----

Change the upload scripts to write the secrets from our passwordstore to
credhub instead of S3.

Update the concourse pipeline and bosh manifests to read secrets from
credhub instead of S3 (this mostly just involves using the `((secret))`
syntax).

Add a make target to remove the secrets from S3 once this has deployed
(NOTE: this script should only be run once the pipeline is reading from
credhub).

How to review
-------------

* Review alongside https://github.com/alphagov/paas-credentials/pull/160 and https://github.com/alphagov/paas-credentials/pull/159
* [x] Run the `upload-all-secrets` make target from this branch against your dev env
* [x] Run the `crosscheck-s3-credhub-secrets` make target from this branch against your dev env and check there are no significant changes
* [x] Run the `create-cloudfoundry` pipeline from this branch against your dev env
* [x] Run the `clean-up-s3-secrets` make target from this branch
* [x] Run the `create-cloudfoundry` pipeline again to confirm that no secrets are being read from S3

## How to release

* [ ] Run the `upload-all-secrets` make target from this branch against:
  * [ ] `stg-lon`;
  * [ ] `prod`;
  * [ ] `prod-lon`.
* [ ] Run the `crosscheck-s3-credhub-secrets` make target to check the secrets in S3 and CredHub are not significantly different in:
  * [ ] `stg-lon`;
  * [ ] `prod`;
  * [ ] `prod-lon`.
* [ ] Merge this PR and wait for the pipelines to finish;
* [ ] Run the `clean-up-s3-secrets` make target against:
  * [ ] `stg-lon`;
  * [ ] `prod`;
  * [ ] `prod-lon`.
* [ ] Once people have done this in their dev environment, review and merge #2068 to remove the temporary Make targets added by this PR.

Who can review
--------------

Not Richard or Tom

### CODE REVIEW

**Comment by richardTowers** [comment]
Rebased on Miki's branch - should rebase cleanly onto master once #2057 is merged.

**Comment by 46bit** [comment]
I'm happy with the code. I'll try it out with my dev environment.

**Comment by richardTowers** [comment]
Miki's extra commit looks good to me - I can't approve it because it's my PR, but 👍

**Comment by richardTowers** [comment]
4d4f942f6b319c7bf25de972dc4d4fdfa31da8f3 seems like overkill to me - I'd expect someone to use `bosh-cli` and then just run `credhub delete /whatever` if they wanted to delete a secret.

**Comment by 46bit** [comment]
@richardTowers I thought it was overkill too, until I saw the 38 lines of config needed before reaching `docker run`.

**Comment by AP-Hunt** [comment]
I ran `make dev upload-all-secrets` without fetching the latest secrets from `paas-pass` first and it error'd. I pulled them down and ran `make dev upload-all-secrets` again. It error'd a second time.

```
Import complete.
Successfully set: 9
Failed to set: 1
 - Credential '/concourse/main/create-cloudfoundry/logit_elasticsearch_api_key' at index 8 could not be set: The credential type cannot be modified. Please delete the credential if you wish to create it with a different type.
```

**Comment by 46bit** [comment]
@AP-Hunt Ah, sorry, that seems to be set already (and to a value of different type!) I had to delete it with `credhub delete …`. I've already done that in `stg-lon`, `prod` and `prod-lon`. At one point this PR included a script with context on doing that, but I removed it.

**Comment by 46bit** [comment]
This isn't an easy thing to review–I think this would ideally be at least two separate PRs.

**Comment by AP-Hunt** [comment]
> I had to delete it with `credhub delete …`. 

Yep, that solved it for me too. Perhaps we can resolve this with a bit of checking before set a value?

```
new_secret = {
    path: "/secret/path",
    type: "password",
    value: "foo",
}
existing_secret = get_secret(new_secret.path)

if existing_secret && existsting_secret.type != new_secret_path {
    delete_secret(new_secret.path)
}

create_secret(new_secret)
```

**Comment by tlwr** [comment]
This monster went down my pipeline just fine

I'm going to pause the staging pipeline and merge this with clean masters of paas-cf, paas-credentials, paas-credentials-high

**Comment by 46bit** [comment]
We got it done!
source-1

**Pull request merged**
