### PR TITLE
[#127449817] Convert unbind_job tests to Ginkgo

### PR DESCRIPTION
**Pull request by dcarley**
## What

So that we can remove Aruba as described in 7f79755.

The significant differences between the old and new tests are:

- assertions on STDOUT *and* STDERR in each test because they are both
  important when the script is consumed in the pipeline
- re-worded test descriptions because they needed to be split into `Context`
  and `It` so that I had somewhere to assign variables

I did experiment with using a function like `unbind` within each `It` block
that took the job name and input YAML. However I settled on using variables
and a combination of `BeforeEach` and `JustBeforeEach` because I think
having named variables makes the test easier to read.

## How to review

1. Check that it tests the same things as before.
1. Check that the Travis tests pass.
1. Optionally, run the tests locally with `make test`.

## Who can review

@keymon because he is working the rest of the referenced story.

### CODE REVIEW

**Comment by keymon** [comment]
You got mis-balanced braces in the `Describe("pipeline manipulation")` and if you fix it, the tests fail :(

```diff
diff --git a/concourse/scripts/unbind_job_test.go b/concourse/scripts/unbind_job_test.go
index 2980b6b..b64a3e5 100644
--- a/concourse/scripts/unbind_job_test.go
+++ b/concourse/scripts/unbind_job_test.go
@@ -111,20 +111,19 @@ jobs:
   - get: paas-cf
     passed: ['some_previous_job']
 `))
+			})
 
-				It("removes passed from paas-cf resource", func() {
-					Eventually(session).Should(gexec.Exit(0))
-					Expect(session.Out.Contents()).To(Equal(`---
+			It("removes passed from paas-cf resource", func() {
+				Eventually(session).Should(gexec.Exit(0))
+				Expect(session.Out.Contents()).To(Equal(`---
 jobs:
 - name: myjob
   plan:
   - get: paas-cf
 `))
-					Expect(session.Err.Contents()).To(BeEmpty())
-				})
+				Expect(session.Err.Contents()).To(BeEmpty())
 			})
 		})
-
 		Context("paas-cf resource within do in plan", func() {
 			BeforeEach(func() {
 				jobName = "myjob"
@@ -136,18 +135,18 @@ jobs:
     - get: paas-cf
       passed: ['some_previous_job']
 `))
+			})
 
-				It("removes passed from paas-cf resource", func() {
-					Eventually(session).Should(gexec.Exit(0))
-					Expect(session.Out.Contents()).To(Equal(`---
+			It("removes passed from paas-cf resource", func() {
+				Eventually(session).Should(gexec.Exit(0))
+				Expect(session.Out.Contents()).To(Equal(`---
 jobs:
 - name: myjob
   plan:
   - do:
     - get: paas-cf
 `))
-					Expect(session.Err.Contents()).To(BeEmpty())
-				})
+				Expect(session.Err.Contents()).To(BeEmpty())
 			})
 		})
 
@@ -162,18 +161,18 @@ jobs:
     - get: paas-cf
       passed: ['some_previous_job']
 `))
+			})
 
-				It("removes passed from paas-cf resource", func() {
-					Eventually(session).Should(gexec.Exit(0))
-					Expect(session.Out.Contents()).To(Equal(`---
+			It("removes passed from paas-cf resource", func() {
+				Eventually(session).Should(gexec.Exit(0))
+				Expect(session.Out.Contents()).To(Equal(`---
 jobs:
 - name: myjob
   plan:
   - aggregate:
     - get: paas-cf
 `))
-					Expect(session.Err.Contents()).To(BeEmpty())
-				})
+				Expect(session.Err.Contents()).To(BeEmpty())
 			})
 		})
 
@@ -190,9 +189,10 @@ jobs:
         passed: ['some_previous_job']", "myjob")
 `))
 
-				It("removes passed from paas-cf resource", func() {
-					Eventually(session).Should(gexec.Exit(0))
-					Expect(session.Out.Contents()).To(Equal(`---
+			})
+			It("removes passed from paas-cf resource", func() {
+				Eventually(session).Should(gexec.Exit(0))
+				Expect(session.Out.Contents()).To(Equal(`---
 jobs:
 - name: myjob
   plan:
@@ -200,8 +200,7 @@ jobs:
     - do:
       - get: paas-cf
 `))
-					Expect(session.Err.Contents()).To(BeEmpty())
-				})
+				Expect(session.Err.Contents()).To(BeEmpty())
 			})
 		})
 	})
@@ -222,10 +221,11 @@ jobs:
       - get: paas-cf
         passed: ['some_previous_job']
 `))
+		})
 
-			It("removes passed from all paas-cf resources", func() {
-				Eventually(session).Should(gexec.Exit(0))
-				Expect(session.Out.Contents()).To(Equal(`---
+		It("removes passed from all paas-cf resources", func() {
+			Eventually(session).Should(gexec.Exit(0))
+			Expect(session.Out.Contents()).To(Equal(`---
 jobs:
 - name: myjob
   plan:
@@ -235,8 +235,7 @@ jobs:
     - do:
       - get: paas-cf
 `))
-				Expect(session.Err.Contents()).To(BeEmpty())
-			})
+			Expect(session.Err.Contents()).To(BeEmpty())
 		})
 	})
 })

```

**Comment by dcarley** [comment]
> You got mis-balanced braces in the Describe("pipeline manipulation") and if you fix it, the tests fail :(

Good catch! I'll investigate..

Do you have any idea why the tests pass as-is?

**Comment by keymon** [comment]
I guess they pass because the `It` was inside of the function pass to the `BeforeEach`, but that function is only called before each `It` that is defined in that `Describe`. But as all the `It` were wrong, there was actually none defined, so it never executed the `BeforeEach` at all and it did not fall.

Hope I explained myself :-D

**Comment by dcarley** [comment]
Fixed 🔨

**Comment by keymon** [comment]
LGTM now

**Pull request merged**
