### PR TITLE
[#115429827] Enable basic auth for kibana

### PR DESCRIPTION
**Pull request by benhyland**
## What

https://www.pivotaltracker.com/story/show/115429827

Use HAProxy from the logsearch release to put http basic auth in front of Kibana.

## How to review

- Deploy the branch
- Run `make dev showenv`, notice that `KIBANA_ADMIN_PASSWORD` is shown
- Visit the logsearch URL
- Verify that http basic auth is required, and that the creds `admin`/`<KIBANA_ADMIN_PASSWORD>` give access

## Who can review

not @benhyland

### CODE REVIEW

**Comment by keymon** [comment]
For consistence with grafana #604  and #606, can we show the password in `make showenv`

Note that the good implementation is #606, the other one broke stuff

**Comment by benhyland** [comment]
@keymon I don't understand what you are asking for.
What do you want done differently?

**Comment by keymon** [comment]
@benhyland sorry, the summary in the card did no mention it and I though you did not implement it. It is fine.

**Comment by benhyland** [comment]
Cool, np then

**Comment by mtekel** [comment]
works correctly, thanks for DRYing passwords script

**Pull request merged**
