### PR TITLE
Upgrade cf-deployment, stemcell and cflinuxfs3

### PR DESCRIPTION
**Pull request by corlettb**
What
----

- Upgrade cf-deployment to v26.5.0
- Upgrade cflinuxfs3 to 0.352.0
- Upgrade jammy stemcell to 1.83

Notes:

- No uaa update this time.

How to review
-------------

[Tested in dev-02.](https://deployer.dev02.dev.cloudpipeline.digital/teams/main/pipelines/create-cloudfoundry/jobs/cf-deploy/builds/365#L63f75b8d:1)

---

🚨⚠️ Please do not merge this pull request via the GitHub UI ⚠️🚨

### CODE REVIEW

**Comment by cadmiumcat** [comment]
It'd be handy to have each as a separate commit. It'll make it easier to search for them if we need to, and to understand issues like the app autoscaler one without having to look through all other changes

**Comment by corlettb** [comment]
> It'd be handy to have each as a separate commit. It'll make it easier to search for them if we need to, and to understand issues like the app autoscaler one without having to look through all other changes

Done

**Review by cadmiumcat — APPROVED** [review]

**Comment by cadmiumcat** [comment]
Thank you!

**Comment by corlettb** [comment]
I've discovered some issues with the autoscaler. I've pulled it out of this PR.

**Pull request closed without merging**
