### PR TITLE
[#183012348] Upgrade cf-deployment to v21.8.0

### PR DESCRIPTION
**Pull request by malcgds**
What
----

* Upgrade cf-deployment checkout to v21.8.0
* Upgrade bionic-stemcell to 1.97 (added in alphagov/paas-bootstrap/pull/515)

How to review
-------------

- Code review - any typos
- Deploy to dev environment 

---

🚨⚠️ Please do not merge this pull request via the GitHub UI ⚠️🚨

### CODE REVIEW

**Comment by whi-tw** [comment]
Tests passing is somewhat blocked by cloudfoundry/cf-deployment/pull/985.

**Comment by cadmiumcat** [comment]
I think this looks good. It'd be helpful to have the white space changes in a different commit (or just not there)

Have you already deployed to a dev environment? or should I do that?

**Comment by cadmiumcat** [comment]
I think this looks good. It'd be helpful to have the white space changes in a different commit (or just not there)

Have you already deployed to a dev environment? or should I do that?

**Comment by cadmiumcat** [comment]
I think this looks good. It'd be helpful to have the white space changes in a different commit (or just not there)

Have you already deployed to a dev environment? or should I do that?

**Comment by cadmiumcat** [comment]
I think this looks good. It'd be helpful to have the white space changes in a different commit (or just not there)

Have you already deployed to a dev environment? or should I do that?

**Review by cadmiumcat — APPROVED** [review]
Much nicer 👍

**Pull request merged**
