### PR TITLE
[#127564379] Fix lrps mapping

### PR DESCRIPTION
**Pull request by saliceti**
## What

Story: [Junk logstash mappings being created & breaking Kibana](https://www.pivotaltracker.com/story/show/131722035)

We have an issue with a log message from the auctioneer. It contains:
`"data":{"lrps":{"df03138b-924d-417e-9743-abf81e577a70-7276869e-d03c-4ffd-9f83-18c366a390c3":[1]},...,"request":"/v1/lrps",...}`
Elasticsearch assumes
`auctioneer.data.lrps.df03138b-924d-417e-9743-abf81e577a70-7276869e-d03c-4ffd-9f83-18c366a390c3`
is the name of a field, because it contains an array of integers. So it creates a mapping for each new LRP GUID.
    
This PR adds a logstash filter that changes the hash to an array containing the GUID strings.
    
This depends on the code from PR
https://github.com/alphagov/paas-logsearch-for-cloudfoundry/pull/1

## How to review
* On an existing environment, search for `auctioneer.request.lrp-auction-handler.create.submitted` in logsearch. You should see fields in the form of `auctioneer.data.lrps.<LRP GUID>`. Run smoke tests if you don't see any
* Deploy with this branch
* Test again, it shouldn't create these fields. Check the data is still there and you can still see the LRP GUIDs

## Note
* This modifies the mapping format of `auctioneer.data.lrps` from `string->[]int` to `[]string`. If you apply the change on an existing index, ES will refuse to index the new log messages. The easiest solution is to delete the index and let ES reindex with the new mapping:

```shell
# curl 10.0.16.10:9200/_cat/indices
green open .kibana             1 1      2 0 182.6kb  92.6kb 
green open logstash-2016.12.15 5 1 635646 0   1.2gb 633.8mb 
# curl -X DELETE 10.0.16.10:9200/logstash-2016.12.15
```

* In production, the change will be active the next day when a new index is used

## How to merge
- When ready, merge PR https://github.com/alphagov/paas-logsearch-for-cloudfoundry/pull/1
- Wait for final release to be built
- Copy the final release yaml snippet from release CI
- Edit commit 8957a8cdf0b95bbb749b8bfe27f8ed82d37e25a4 and paste the snippet
- Push
- Merge this PR

## Who can review
Not @combor or me

### CODE REVIEW

**Comment by keymon** [comment]
@saliceti @combor could you add the paas-logsearch-for-cloudfoundry project to the https://github.com/alphagov/paas-release-ci project and start using that?

thx

**Comment by saliceti** [comment]
I would do it but to test it I need to create 2 new buckets and we're hitting the limit at the moment.

**Comment by saliceti** [comment]
Done

**Comment by keymon** [comment]
@saliceti do not ad  11200f7 , that is done in #655 and #662

**Comment by keymon** [comment]
@saliceti added that in https://github.com/alphagov/paas-cf/pull/655/commits/c717f0fb4a145270afedc573d68c1ef4ff538e5c

**Comment by mtekel** [comment]
works well, merging

**Pull request merged**
