### PR TITLE
prod-lon: bump number of cells to 150

### PR DESCRIPTION
**Pull request by risicle**
What
----

Metrics suggest we're edging over 66% capacity in london.

How to review
-------------

:eyes: 

---

🚨⚠️ Please do not merge this pull request via the GitHub UI ⚠️🚨

### CODE REVIEW

**Comment by risicle** [comment]
I have no brain.

**Comment by risicle** [comment]
I do wonder if we can revise that doppler# recommendation what with recent changes. The doppler machines have very low utilization.

**Comment by risicle** [comment]
Now `log_api`, assuming `log_cache` too.

**Review by schmie — APPROVED** [review]
:+1: there must be abetter way to not chain the linter notices :/

**Pull request merged**
