### PR TITLE
[#131876783] Migration from paas-cf to paas-bootstrap

### PR DESCRIPTION
**Pull request by keymon**
[#131876783 Migrate paas-cf to paas-bootstrap](https://www.pivotaltracker.com/story/show/131876783)

**NB: Please review but do not merge over holiday period**

What?
---

We want to use paas-bootstrap project to create the initial VPC, bosh and concourse deployer, and remove the required logic from paas-cf.

For that we want to move all the logic to create VPC, bosh and concourse to https://github.com/alphagov/paas-bootstrap and remove it from this project.

In this PR:
 * We remove all the logic implemented in paas-bootstrap: VPC creation, bosh, concourse, etc.
 * We add some code to migrate some small things: rename pipelines, etc.

Dependencies
-----------

In the PR https://github.com/alphagov/paas-bootstrap/pull/26 we added logic to do the migration, and this PR must be tested and applied in conjuction with the later.

How to review?
---------------

Do a code review and check that everything makes sense.

Test it by running: `BRANCH=$(git rev-parse --abbrev-ref HEAD) DEPLOY_ENV=... make dev pipelines` after doing the migration described in https://github.com/alphagov/paas-bootstrap/pull/26.

Who?
---

Anyone but @keymon, @alext or @dcarley

### CODE REVIEW

**Comment by timmow** [comment]
There is a typo in the commit message for 10dfd86f1f6d44784751ea91d8b8b714688d144c

**Comment by saliceti** [comment]
There is a small typo in 10dfd86 title

**Comment by saliceti** [comment]
There are 2 FIXME blocks in c66fb99 and f273e95. Could we put them in separate commits so we can revert them easily later on?

**Comment by timmow** [comment]
All looks good to me

**Comment by keymon** [comment]
Thx. I will rebase, fix the conflicts and fix the commented issues.

**Comment by keymon** [comment]
@saliceti rebased and commits fixed and split

**Pull request merged**
