### PR TITLE
[#121933113]  Enable HTTP healthcheck on router ELB

### PR DESCRIPTION
**Pull request by combor**
## What

This is follow up to https://github.com/alphagov/paas-cf/pull/341 to enable custom haproxy healthcheck which sends specific user-agent to gorouter. 

Please merge it after its parent has been deployed to production.
 
## How to review

Apply on top of existing env and check if availability test passes.

## Who can review

Not @saliceti or @combor

### CODE REVIEW

**Comment by alext** [comment]
> Please merge it after its parent.

Should this be after its parent has been deployed to production?

**Comment by combor** [comment]
Yes, actually it can happen that if you merge two PRs in one minute time slot they will be delivered together. Not sure if it's a feature or bug though.

**Comment by keymon** [comment]
I will merge as soon as #341 hits prod.

**Comment by keymon** [comment]
Rebased with master after merging #341 

I will wait until this gets deployed in prod.

**Comment by keymon** [comment]
Tested again, and it work like charm. Will merge once #345 is deployed in prod.

**Comment by keymon** [comment]
#345 has been deployed \o/... I will merge this :+1:

**Pull request merged**
