### PR TITLE
[#154959067] Remove UAA ELB and CloudFront Distributions

### PR DESCRIPTION
**Pull request by henrytk**
## What

Now that UAA, the Product Pages, and the Tech Docs all use the system domain ELB we can remove this infrastructure.

## How to review

⚠️ wait until https://github.com/alphagov/paas-cf/pull/1218 is deployed to production before merging. This will allow time for DNS caches to expire.

~~⚠️ once https://github.com/alphagov/paas-cf/pull/1218 is merged this should be rebased on master.~~ Done.

### Product Pages/Tech Docs

Ideally you are the person that reviewed https://github.com/alphagov/paas-cf/pull/1218 and you have the CloudFront Distributions and the product page/tech docs deployed.

* ~~Run the `make` target with `ACTION=plan`, check everything looks okay~~
* ~~Run the `make target with `ACTION=apply`.~~
* ~~The apps should still serve traffic.~~

**EDIT:** As per @alext's suggestion, the `make` target and script have been removed, so when you are happy with the code change you can run `make <env> setup_cdn_instances ACTION=destroy` for _all_ environments from the master branch, _then_ merge.

### UAA

Deploy from this branch and make sure all tests pass.

## Who can review

Anyone but me or @camelpunch

### CODE REVIEW

**Comment by alext** [comment]
I think we could remove all the `setup_cdn_instances` related code in this PR (including the make target, and associated scripts...).

The merge instructions could then be to run `make <env> setup_cdn_instances ACTION=destroy` from master before merging this.

**Comment by alext** [comment]
It's not currently possible to run the cdn instances terraform from this branch. It errors with:
```
Error: No configuration files found!
```

This is also why Travis is failing.

**Comment by henrytk** [comment]
> I think we could remove all the `setup_cdn_instances` related code in this PR (including the make target, and associated scripts...).

Done.

**Comment by alext** [comment]
I've run the CDN instance destroy in production (they weren't present in staging).

**Pull request merged**
