### PR TITLE
[#117131037] Fixing the build: Double tags in stage

### PR DESCRIPTION
**Pull request by keymon**
[#117131037 Fixing the build: Double tags in stage](https://www.pivotaltracker.com/story/show/117131037)

What
----

It seems that CI run twice and created a double tag of stage. Then staging tag-release failed because the script does not handle well two tags.

Scope
-----

In this PR we add code so that

 - Not fail if there are two tags poiting to HEAD
 - Do not allow double tagging

Additionally, to help testing I added code to optionally disable git push

How to test
-----------

As we lack of a proper unit testing for this script, you can use this
minimum Dockerfile.

```
cat <<EOF > Dockerfile
FROM governmentpaas/git-ssh

WORKDIR /tmp
RUN mkdir -p /tmp/paas-cf
RUN cd /tmp/paas-cf && \
    git init && \
    git commit --allow-empty -m "First commit" && \
    git tag previous-0.0.1 && \
    git tag previous-0.0.2

RUN mkdir -p /tmp/git-keys && cd  /tmp/git-keys  && \
    ssh-keygen -f git-key -N '' && \
    tar -cvzf git-keys.tar.gz git-key git-key.pub

ENV GIT_PUSH=false

ADD ./concourse/scripts/tag-release.sh /tmp/

RUN cd /tmp && /tmp/tag-release.sh next- testaccount testenv 'previous-*' && \
    cd /tmp/paas-cf && git tag && \
    cd /tmp/paas-cf && git remote remove ssh && \
    cd /tmp && /tmp/tag-release.sh next- testaccount testenv 'previous-*' && \
    cd /tmp/paas-cf && git tag
EOF
```

Run it as: `docker build --force-rm=true --no-cache=true .` in the repo directory

Who?
----

Anyone but @keymon

### CODE REVIEW

**Comment by dcarley** [comment]
I've created [#117133525](https://www.pivotaltracker.com/story/show/117133525) to test this in the future.

shellcheck failed the build: https://travis-ci.org/alphagov/paas-cf/builds/121388960#L657

**Comment by dcarley** [comment]
> It seems that CI run twice and created a double tag of stage

Do you know how this happened?

**Comment by keymon** [comment]
Fixed the shellcheck. BTW, annoying in my local shellcheck it did not fail.

It happened because there were two runs of the same commit in CI:
 * https://deployer.master.ci.cloudpipeline.digital/pipelines/create-bosh-cloudfoundry/jobs/pipeline-lock/builds/17
 * https://deployer.master.ci.cloudpipeline.digital/pipelines/create-bosh-cloudfoundry/jobs/pipeline-lock/builds/18

But I don't know how it was triggered twice. Concourse does not say.

**Comment by alext** [comment]
> But I don't know how it was triggered twice. Concourse does not say.

It's possible this was related to rolling out the pipeline locking. There was some odd triggering happening while the pipelines were being updated.

**Comment by keymon** [comment]
I think in GoCD  it was recorded why the job/pipeline was triggered, which was nice.

**Comment by dcarley** [comment]
LGTM, and I appreciate the test instructions :+1:

**Pull request merged**
