### PR TITLE
[#127350531] 	avail-tests: Test for vegeta lib 404 behaviour

### PR DESCRIPTION
**Pull request by dcarley**
## What

Our availability-tests print the number of non-200 responses and fail if
`metrics.Success` is less than 100%. When looking at the tests and the
documentation for Vegeta, it wasn't clear to me whether `metrics.Success`
included 404 responses or not. This is important because Cloud Foundry's
gorouter will return 404s for an application that exists but has no healthy
instances.

After looking in the code I found that Vegeta does not consider responses
with a status code of 400 or more as successful and that our test is
correct:

- https://github.com/tsenart/vegeta/blob/166e3050f5a8b2f6d3d2cb03e7baa430f019395d/lib/metrics.go#L100-L102

However I think it would be useful to have a test that asserts this
particular behaviour of Vegeta, to save anyone else going on the same hunt
and make us aware in the unlikely event that Vegeta's behaviour changes.

## How to review

1. Look at the code to see if the test makes sense and has value.
1. Deploy this branch to your environment.
1. Run the pipeline from the beginning and confirm that the availability-tests pass.

## Who can review

Not @dcarley

### CODE REVIEW

**Comment by dcarley** [comment]
I've noticed that I have some `vendor/` files that aren't committed after running `godep save`. I'm not sure if they *should* be committed though and why other parts of `ginkgo` and `gomega` aren't in that directory structure. Anyone know?

```
➜  platform-tests git:(feature/127350531-test_vegeta_404) ✗ git st
On branch feature/127350531-test_vegeta_404
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        src/availability/vendor/github.com/golang/
        src/availability/vendor/github.com/onsi/

nothing added to commit but untracked files present (use "git add" to track)
➜  platform-tests git:(feature/127350531-test_vegeta_404) ✗ find src/availability/vendor/github.com/{golang,onsi}
src/availability/vendor/github.com/golang
src/availability/vendor/github.com/golang/protobuf
src/availability/vendor/github.com/golang/protobuf/LICENSE
src/availability/vendor/github.com/golang/protobuf/proto
src/availability/vendor/github.com/golang/protobuf/proto/clone.go
src/availability/vendor/github.com/golang/protobuf/proto/decode.go
src/availability/vendor/github.com/golang/protobuf/proto/encode.go
src/availability/vendor/github.com/golang/protobuf/proto/equal.go
src/availability/vendor/github.com/golang/protobuf/proto/extensions.go
src/availability/vendor/github.com/golang/protobuf/proto/lib.go
src/availability/vendor/github.com/golang/protobuf/proto/Makefile
src/availability/vendor/github.com/golang/protobuf/proto/message_set.go
src/availability/vendor/github.com/golang/protobuf/proto/pointer_reflect.go
src/availability/vendor/github.com/golang/protobuf/proto/pointer_unsafe.go
src/availability/vendor/github.com/golang/protobuf/proto/properties.go
src/availability/vendor/github.com/golang/protobuf/proto/text.go
src/availability/vendor/github.com/golang/protobuf/proto/text_parser.go
src/availability/vendor/github.com/onsi
src/availability/vendor/github.com/onsi/gomega
src/availability/vendor/github.com/onsi/gomega/ghttp
src/availability/vendor/github.com/onsi/gomega/ghttp/handlers.go
src/availability/vendor/github.com/onsi/gomega/ghttp/test_server.go
src/availability/vendor/github.com/onsi/gomega/LICENSE
```

**Comment by keymon** [comment]
No idea why there are not include. I would include them.

**Comment by keymon** [comment]
LGTM, go ahead if you want to add the missing vendor files. I will merge after.

**Comment by dcarley** [comment]
> No idea why there are not include. I would include them.

I think it might have been from a previous invocation of `godep`. Running `godep save` again doesn't reproduce them. So I'm going to leave it as-is.

I'm also not really clear why the `Packages: ["./..."]` has been removed from `Godeps.json`.

If I run `godep save ./...` I get:
```
➜  availability git:(feature/127350531-test_vegeta_404) ✗ godep save ./...
godep: dirty working tree (please commit changes): /Users/dcarley/projects/gocode/src/github.com/alphagov/paas-cf/tests/helpers
godep: error loading dependencies
```

If I run `godep save ./..` it removes everything from `Deps: []` and `vendor/`.

**Comment by keymon** [comment]
+1

**Pull request merged**
