### PR TITLE
[#136027817] Cleanup CF terraform

### PR DESCRIPTION
**Pull request by mtekel**
## What

[Cleanup terraform](https://www.pivotaltracker.com/n/projects/1275640/stories/136027817)
Tidy up our TF repositories. It turns out most of them were OK, so all the cleanup is in cloudfoundry repo.

## How to review

Checkout this branch. Apply. You should see 2 changes in SGs applied, this is because of last commit which fixes CF workaround. Without this commit, there are no changes. Verify that there is no outage and that tests pass.

## Who can review

not @mtekel

### CODE REVIEW

**Comment by dcarley** [comment]
I haven't got time to review right now, but just want to add that this looks good - code is easier to read, commits are straightforward to review, file renames are preserved in git history, and it got rid of a FIXME 👍

**Comment by dcarley** [comment]
I'm available after all. Reviewing.

**Comment by dcarley** [comment]
Tests out fine. Couple of minor requests for commit messages:

1. Could you change the subject of the commit messages for 56c5e1db496b84d99093a1a23eaa40cb6922fb78, 9bf31fee83d82fcc56a3b04c9a8682302962561b and 27eaf9e24361ce794e252c0f9b620c06800786ed to make it clear that they're only renaming files like b6d3b8329f669bd40f6a4be2348f5bfc62812f00 and ad7d942c3acf19bc05996a3c7c30bbb40bfe593b do?
1. 487d16985b05b7e9ec7612843d32524ea3e610f5 says "CF version" but I think it means "Terraform version"?

**Comment by mtekel** [comment]
fixed

**Comment by dcarley** [comment]
Thanks :shipit:

**Pull request merged**
