### PR TITLE
Remove the `paas_currency_real_ratio` metric

### PR DESCRIPTION
**Pull request by AP-Hunt**
What
----

The API we used to get the value is now behind a pay wall. We haven't had data for the metric since 4th April, and nobody has noticed, so we can safely say we don't need it.

image

How to review
-------------

Make sure I didn't miss anything

---

🚨⚠️ Please do not merge this pull request via the GitHub UI ⚠️🚨

### CODE REVIEW

**Review by paroxp — APPROVED** [review]
Don't we have some alerts based on this?

**Comment by AP-Hunt** [comment]
> Don't we have some alerts based on this?

I couldn't find any:
```
$ echo $PWD; git grep -r 'paas_currency_real_ratio'; echo $?
...github.com/alphagov/paas-cf
1
```

**Comment by 46bit** [comment]
Not since https://github.com/alphagov/paas-cf/pull/2147

**Comment by paroxp** [comment]
Thanks Miki!

**Pull request merged**
