### PR TITLE
[#132681767] Upgrade stemcells for bosh to 3263.8

### PR DESCRIPTION
**Pull request by keymon**
[#132681767 Upgrade BOSH #2: stemcell, CPI and new features](https://www.pivotaltracker.com/story/show/132681767)

What
----

We upgraded bosh release, and later the CF stemcell. Now we want to upgrade the stemcell for bosh.

~~We also upgrade the stemcell of concourse, to keep consistency.~~

The change basically changes from the kernel 3.3 to 4.4

~~In the case of concourse, the change is only minor bugs.~~

Dependencies
-----------------

I suggest to merge #565 first, but it is not really required.

How to review
-------------

 * Check that the change makes sense (urls, hash)
 * Optionally deploy the environment and check that bosh is working (e.g. run all the pipeline). ~~The same for concourse.~~

~~I do not think it is required to redeploy concourse in all the environments after this is merged.~~

Who?
----

Anyone but @keymon

### CODE REVIEW

**Comment by keymon** [comment]
@mtekel does not want concourse to be upgraded without a stronger reason. Dropping the commit.

```
$ git show 4860a31e88a398c4c7a42117b1dfd25e9a0e6caf
commit 4860a31e88a398c4c7a42117b1dfd25e9a0e6caf
Author: Hector Rivas Gandara <keymon@gmail.com>
Date:   Wed Oct 26 16:59:57 2016 +0100

    Update the concourse stemcell to 6263.8 as in CF
    
    We have upgraded the CF stemcell to 6263.8 in #565.
    
    We upgrade to the same stemcell in concourse.

diff --git a/manifests/concourse-manifest/concourse-base.yml b/manifests/concourse-manifest/concourse-base.yml
index 834a6ff..181a14e 100644
--- a/manifests/concourse-manifest/concourse-base.yml
+++ b/manifests/concourse-manifest/concourse-base.yml
@@ -22,8 +22,8 @@ resource_pools:
   - name: concourse
     network: concourse
     stemcell:
-      url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3263.5
-      sha1: a4a3b387ee81cd0e1b73debffc39f0907b80f9c6
+      url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3263.8
+      sha1: 95ecc2709ac62f21d0a1c6cac023585c3919b825
     cloud_properties:
       instance_type: m4.large
       availability_zone: (( grab terraform_outputs.zone0 ))
```

**Comment by mtekel** [comment]
It would be nice to merge this with #570. It would mean one less (slow, because bosh needs to recompile) test, one less bosh deploy. And thus faster merge.

**Comment by keymon** [comment]
I merged this into #570. If you merge #570, this will be automatically market as merged.

**Comment by mtekel** [comment]
Indeed, this was marked as merged, even though I only merged #570

**Pull request merged**
