### PR TITLE
rds-broker: 1.34.0 -> 1.36.0

### PR DESCRIPTION
**Pull request by risicle**
What
----

~*This depends on https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/246 and will need its docker image tags changed to the final value once that is merged*~

https://www.pivotaltracker.com/story/show/183025078

This deploys the improvements from https://github.com/alphagov/paas-rds-broker/pull/160 ~and adds custom broker acceptance test coverage for it.~

How to review
-------------

Deploy to a dev env, look at the custom broker acceptance tests.

---

🚨⚠️ Please do not merge this pull request via the GitHub UI ⚠️🚨

### CODE REVIEW

**Review by cadmiumcat — APPROVED** [review]
yes - obviously once the tags are right and all that

**Comment by risicle** [comment]
Can't fix those till https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/246 is merged

**Comment by risicle** [comment]
Ok have removed all the acceptance test complications from this PR, we will worry about them in a separate story.

**Review by whpearson — APPROVED** [review]
This worked when I deployed it previously.

**Pull request merged**
