### PR TITLE
[#112135729] Combine pipeline scripts

### PR DESCRIPTION
**Pull request by dcarley**
## What

Combine the pipeline config scripts for Deployer, MicroBOSH and CloudFoundry. So that we only need to maintain and run a single script to configure the pipelines for each component.

## How to review

Run the steps described in the README against an existing Bootstrap Concourse and Deployer Concourse. Observe no changes to the pipeline configurations.

## Who can review

Not @dcarley

### CODE REVIEW

**Comment by dcarley** [comment]
Re-opened with an actual description this time.

**Comment by saliceti** [comment]
Tested successfully.

**Comment by alext** [comment]
Note: We've agreed that #73 will be merged before this one, so please **do not merge** until #73 has been merged.

**Comment by alext** [comment]
This needs rebasing now that #73 has been merged.

**Comment by keymon** [comment]
LGTM :+1:

**Pull request merged**
