### PR TITLE
Update paas docker images to pick up new bosh-cli-v2

### PR DESCRIPTION
**Pull request by corlettb**
What
----

Update paas docker images to pick up new bosh-cli-v2

How to review
-------------

Deployed in dev-04

---

🚨⚠️ Please do not merge this pull request via the GitHub UI ⚠️🚨

### CODE REVIEW

**Comment by risicle** [comment]
Missed concourse/pipelines/autodelete-cloudfoundry.yml

Although perhaps we should be deleting that pipeline.

**Comment by corlettb** [comment]
> Missed concourse/pipelines/autodelete-cloudfoundry.yml
> 
> Although perhaps we should be deleting that pipeline.

Updated.

**Comment by risicle** [comment]
(simple rebase)

**Review by risicle — APPROVED** [review]
WFM

**Pull request merged**
