### PR TITLE
[#126608153] Use govuk-lint gem to lint our code

### PR DESCRIPTION
**Pull request by keymon**
[#126608153 Use govuk-lint gem to keep our ruby code tidy](https://www.pivotaltracker.com/story/show/126608153)

What
====

We want adopt the govuk-lint gem in our ruby build process, since govuk have already defined rules for a well-formatted ruby code.

This gem is based on rubocop and we can replace it in our dependencies, enable all the Cops and fix the required offences.

Dependencies
-----------------

It currently fails in travis because we can not customise  the exclude path in govuk-lint. We should wait for this to be merged and update our dependencies: ~~https://github.com/alphagov/govuk-lint/pull/56~~ https://github.com/alphagov/govuk-lint/pull/57

How to review?
------------

 * Review the code.
 * Check the tests run OK locally and on travis.
 * check that the modified scripts work (run all pipeline once)
 * merge this PR

Who?
---

Anyone but @keymon

### CODE REVIEW

**Comment by keymon** [comment]
This is failing because we are not excluding the vendor modules.

I think our `Exclude` in `.rubocop.yml` is not working because it is defined in the [upper level here](https://github.com/alphagov/govuk-lint/blob/master/configs/rubocop/all.yml#L8-L10)

We might need to fork govuk-lint :(

**Comment by dcarley** [comment]
> This is failing because we are not excluding the vendor modules.
> 
> I think our Exclude in .rubocop.yml is not working because it is defined in the upper level here

There are some other projects that seem to do this and I presume as successful: https://github.com/search?utf8=%E2%9C%93&q=user%3Aalphagov+filename%3A.rubocop.yml+exclude&type=Code&ref=searchresults

> We might need to fork govuk-lint :(

Fortunately the people that can merge changes aren't too far away :)

**Comment by keymon** [comment]
I used a forked version in https://github.com/alphagov/paas-cf/pull/427/commits/3c998362f4d1408aad63d2a5f03d92513e5b8b76, so the PR can be reviewed for the time being :)

**Comment by keymon** [comment]
https://github.com/alphagov/govuk-lint/pull/56 has been merged!

**Comment by dcarley** [comment]
The `govuk-lint` change has been released as version 1.2.1 🎉 

- https://github.com/alphagov/govuk-lint/pull/57
- https://rubygems.org/gems/govuk-lint/versions/1.2.1

Could you rebase the `Gemfile` changes?

**Comment by keymon** [comment]
Updated!

**Pull request merged**
