### PR TITLE
[#110234556] Initiate CF deploy from Concourse

### PR DESCRIPTION
**Pull request by timmow**
**What**

We want to merge the existing manifests from [cf-terraform](https://github.com/alphagov/cf-terraform) into this repository, including full history

**How this PR should be reviewed**

This PR should reviewed in the following context:

* I can see the full history from cf-terraform/cf-manifest directory in the manifests/cf-manifest directory of this repo
* I understand the git commands contained in [this gist](https://gist.github.com/timmow/94b0b6b89d0d394e110b) used to filter the branch

**How to test this PR**
Check the branch out and look at the history

It might help to run through the steps in [this gist](https://gist.github.com/timmow/94b0b6b89d0d394e110b) in order to help understand what is happening

**Who should review this PR**

* Anyone but me

### CODE REVIEW

**Comment by timmow** [comment]
The commits look out of order on the  PR interface, but seem fine in git log...

**Comment by dcarley** [comment]
Should we add the additional rspec directory to the Travis test matrix? https://github.com/alphagov/paas-cf/blob/vanilla_cf_prototype_split/.travis.yml#L13

(passing comment, not reviewing this fully)

**Comment by timmow** [comment]
@dcarley I've updated the `travis.yml` to include this and all the tests pass

**Comment by dcarley** [comment]
I think this looks GTG.

**Pull request merged**
